Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Failed to run custom action 'action_joke'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_joke'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Failed to run custom action 'action_joke'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_joke'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Failed to run custom action 'action_joke'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook
Encountered an exception while running action 'action_joke'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 313, in run
    response.raise_for_status()
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_core/actions/action.py", line 334, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))

/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             OPTIONS, GET, HEAD             /static/[filename]
custom_webhook.health                              OPTIONS, GET, HEAD             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Starting new HTTP connection (1): localhost
Creating a new tracker for id 'default'.
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Received user message 'joke' with intent '{'name': 'joke', 'confidence': 0.5980553207947764}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	name: None
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '7'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_joke' with prob 1.00.
Calling action endpoint to run action 'action_joke'.
Starting new HTTP connection (1): localhost
http://localhost:5055 "POST /webhook HTTP/1.1" 200 138
Action 'action_joke' ended with events '["BotUttered(text: Chuck Norris doesn't play god. Playing is for children., data: null)"]'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
http://localhost:5005 "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 None
Starting new HTTP connection (1): localhost
Recreating tracker for id 'default'
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Received user message 'joke' with intent '{'name': 'joke', 'confidence': 0.5980553207947764}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	name: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '7'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_joke' with prob 1.00.
Calling action endpoint to run action 'action_joke'.
Starting new HTTP connection (1): localhost
http://localhost:5055 "POST /webhook HTTP/1.1" 200 276
Action 'action_joke' ended with events '["BotUttered(text: Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous., data: null)"]'
Bot utterance 'BotUttered(text: Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '0'
http://localhost:5005 "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 None
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Starting new HTTP connection (1): localhost
Recreating tracker for id 'default'
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Received user message 'joke' with intent '{'name': 'joke', 'confidence': 0.5980553207947764}' and entities '[]'
Logged UserUtterance - tracker now has 11 events
Current slot values: 
	name: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '7'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_joke' with prob 1.00.
Calling action endpoint to run action 'action_joke'.
Starting new HTTP connection (1): localhost
http://localhost:5055 "POST /webhook HTTP/1.1" 200 222
Action 'action_joke' ended with events '['BotUttered(text: Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds., data: null)']'
Bot utterance 'BotUttered(text: Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}]
There is a memorised next action '0'
http://localhost:5005 "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 None
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Starting new HTTP connection (1): localhost
Recreating tracker for id 'default'
/home/stephch/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Received user message 'name' with intent '{'name': 'greet', 'confidence': 0.30873337120446764}' and entities '[]'
Logged UserUtterance - tracker now has 16 events
Current slot values: 
	name: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_joke': 1.0}, {'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_name' with prob 1.00.
Action 'utter_name' ended with events '[]'
Bot utterance 'BotUttered(text: Hey there! Tell me your name., data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
http://localhost:5005 "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 None
Current tracker state [{'prev_action_joke': 1.0, 'intent_joke': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_name': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
